# -*- coding: utf-8 -*-
"""Studying.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rRw5BbMhzWzrmCSypvdCLVLJ_7bYqg5R
"""
# 📝 Exercício 1: Manipulação de strings e uso de métodos básicos
nome_completo=str(input('Digite seu nome completo: '))
primeiro_nome = nome_completo.split()[0]
print('Analisando seu nome...')
print('Seu nome em maiúsculas é {}'.format(nome_completo.upper()))
print('Seu nome em minúsculas é {}'.format(nome_completo.lower()))
print('Seu nome tem ao todo tem {} letras'.format(len(nome_completo) - nome_completo.count(' ')))
print('Seu primeiro nome é {} e ao todo tem {} letras'.format(primeiro_nome, len(primeiro_nome)))

# 📝 Exercício 2: Trabalhando com datas e bibliotecas datetime e math
import datetime
import math

data_nascimento=(input('Digite sua data de nascimento: ')).strip()
format_data='%d/%m/%Y'
data= datetime.datetime.strptime(data_nascimento, format_data)
agora= datetime.datetime.now()
diferença= agora - data
idade_arrendondada= math.floor(diferença.days/365)
print('Você tem {} anos'.format(idade_arrendondada))

# 📝 Exercício 3: Praticando operadores aritméticos e extração de dígitos com divisão inteira e módulo
num=int(input('Digite um número de 0 a 9999: '))
u=num // 1 % 10
d= num // 10 % 10
c= num // 100 % 10
m= num // 1000 %10
print('Analisando o número {}'.format(num))
print('Unidade: {}'.format(u))
print('Dezena: {}'.format(d))
print('Centena: {}'.format(c))
print('Milhar: {}'.format(m))

# 📝 Exercício 4: Trabalhando com strings, listas e índices
nome=str(input('Digite seu nome completo: ')).strip()
nome_completo= nome.split()
primeiro_nome= nome_completo[0]
último_nome= nome_completo[-1]
print('Muito prazer em te conhecer!')
print('Seu primeiro nome é {}'.format(primeiro_nome))
print('Seu último nome é {}'.format(último_nome))

# 📝 Exercício 5: Trabalhando com listas, funções embutidas max() e min()
primeiro= int(input('Primeiro valor: '))
segundo= int(input('Segundo valor: '))
terceiro= int(input('Terceiro valor: '))

valores= [primeiro, segundo, terceiro]
valores_max= max(valores)
valores_min= min(valores)

print('O maior valor é: {}'.format(valores_max))
print('O menor valor é: {}'.format(valores_min))

# 📝 Exercício 6: Condicional simples (if/else) para cálculo 
salario= float(input('Qual o salário do funcionário? R$ '))
if salario <= 1250:
  novo= (salario * 0.15) + salario
else:
  novo= (salario * 0.10) + salario

print('Quem ganhava R${:.2f} passa a ganhar R${:.2f} agora'.format(salario, novo))

# 📝 Exercício 7: Trabalhando com cores no terminal
print('\33[1;34;45mOlá mundo')

# 📝 Exercício 8: Uso de bibliotecas e lógica condicional 
from datetime import date
ano= int(input('Que ano quer analisar? Coloque 0 para analisar o ano atual: '))
if ano == 0:
  ano= date.today().year
if ano % 4 == 0 and ano % 100 != 0 or ano % 400 == 0:
  print ('O ano {} é bissexto'.format(ano))
else:
  print ('O ano {} não é bissexto'.format(ano))

# 📝 Exercício 9: Uso de geração de números aleatórios e estrutura condicional simples
from random import randint
computador= randint(0, 5)
print('-=-'*20)
print('Vou pensar em um número, tente adivinhar...')
print('-=-'*20)
jogador= int(input('Em que número eu pensei? '))
if computador == jogador:
  print('Parabéns, você acertou!')
else:
  print('Errou! :(')

# 📝 Exercício 10: Condicional com cálculo de multa baseado em limite de velocidade
velocidade= float(input('Qual a velocidade atual do carro? '))
multa= (velocidade - 80) * 7
if velocidade > 80:
  print('MULTADO! Você excedeu o limite da via que é de 80km/h.')
  print('Você deve pagar uma multa de R${:.2f}'.format(multa))
else:
  print('Tenha um bom dia! Dirija com segurança.')

# 📝 Exercício 11: Verificação de número par ou ímpar usando operador módulo
num= float(input('Me diga um número: '))
if num % 2 == 0:
  print('Este número é par.')
else:
  print('Este número é ímpar')

# 📝 Exercício 12: Condicional com cálculo de preço baseado na distância da viagem
distancia= float(input('Qual a distância da sua viagem em km? '))
print('Você está prestes a começar uma viagem de {:.0f}km.'.format(distancia))
if distancia <= 200:
  print('O preço da sua passagem é R${:.2f}'.format(distancia * 0.50))
else:
  print('O preço da sua passagem é R${:.2f}'.format(distancia * 0.45))