# -*- coding: utf-8 -*-
"""Studying.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rRw5BbMhzWzrmCSypvdCLVLJ_7bYqg5R
"""
# 📝 Exercício 1: Manipulação de strings e uso de métodos básicos
nome_completo=str(input('Digite seu nome completo: '))
primeiro_nome = nome_completo.split()[0]
print('Analisando seu nome...')
print('Seu nome em maiúsculas é {}'.format(nome_completo.upper()))
print('Seu nome em minúsculas é {}'.format(nome_completo.lower()))
print('Seu nome tem ao todo tem {} letras'.format(len(nome_completo) - nome_completo.count(' ')))
print('Seu primeiro nome é {} e ao todo tem {} letras'.format(primeiro_nome, len(primeiro_nome)))

# 📝 Exercício 2: Trabalhando com datas e bibliotecas datetime e math
import datetime
import math

data_nascimento=(input('Digite sua data de nascimento: ')).strip()
format_data='%d/%m/%Y'
data= datetime.datetime.strptime(data_nascimento, format_data)
agora= datetime.datetime.now()
diferença= agora - data
idade_arrendondada= math.floor(diferença.days/365)
print('Você tem {} anos'.format(idade_arrendondada))

# 📝 Exercício 3: Praticando operadores aritméticos e extração de dígitos com divisão inteira e módulo
num=int(input('Digite um número de 0 a 9999: '))
u=num // 1 % 10
d= num // 10 % 10
c= num // 100 % 10
m= num // 1000 %10
print('Analisando o número {}'.format(num))
print('Unidade: {}'.format(u))
print('Dezena: {}'.format(d))
print('Centena: {}'.format(c))
print('Milhar: {}'.format(m))

# 📝 Exercício 4: Trabalhando com strings, listas e índices
nome=str(input('Digite seu nome completo: ')).strip()
nome_completo= nome.split()
primeiro_nome= nome_completo[0]
último_nome= nome_completo[-1]
print('Muito prazer em te conhecer!')
print('Seu primeiro nome é {}'.format(primeiro_nome))
print('Seu último nome é {}'.format(último_nome))

# 📝 Exercício 5: Trabalhando com listas, funções embutidas max() e min()
primeiro= int(input('Primeiro valor: '))
segundo= int(input('Segundo valor: '))
terceiro= int(input('Terceiro valor: '))

valores= [primeiro, segundo, terceiro]
valores_max= max(valores)
valores_min= min(valores)

print('O maior valor é: {}'.format(valores_max))
print('O menor valor é: {}'.format(valores_min))

# 📝 Exercício 6: Condicional simples (if/else) para cálculo 
salario= float(input('Qual o salário do funcionário? R$ '))
if salario <= 1250:
  novo= (salario * 0.15) + salario
else:
  novo= (salario * 0.10) + salario

print('Quem ganhava R${:.2f} passa a ganhar R${:.2f} agora'.format(salario, novo))

# 📝 Exercício 7: Trabalhando com cores no terminal
print('\33[1;34;45mOlá mundo')

# 📝 Exercício 8: Uso de bibliotecas e lógica condicional 
from datetime import date
ano= int(input('Que ano quer analisar? Coloque 0 para analisar o ano atual: '))
if ano == 0:
  ano= date.today().year
if ano % 4 == 0 and ano % 100 != 0 or ano % 400 == 0:
  print ('O ano {} é bissexto'.format(ano))
else:
  print ('O ano {} não é bissexto'.format(ano))

# 📝 Exercício 9: Uso de geração de números aleatórios e estrutura condicional simples
from random import randint
computador= randint(0, 5)
print('-=-'*20)
print('Vou pensar em um número, tente adivinhar...')
print('-=-'*20)
jogador= int(input('Em que número eu pensei? '))
if computador == jogador:
  print('Parabéns, você acertou!')
else:
  print('Errou! :(')

# 📝 Exercício 10: Condicional com cálculo de multa baseado em limite de velocidade
velocidade= float(input('Qual a velocidade atual do carro? '))
multa= (velocidade - 80) * 7
if velocidade > 80:
  print('MULTADO! Você excedeu o limite da via que é de 80km/h.')
  print('Você deve pagar uma multa de R${:.2f}'.format(multa))
else:
  print('Tenha um bom dia! Dirija com segurança.')

# 📝 Exercício 11: Verificação de número par ou ímpar usando operador módulo
num= float(input('Me diga um número: '))
if num % 2 == 0:
  print('Este número é par.')
else:
  print('Este número é ímpar')

# 📝 Exercício 12: Condicional com cálculo de preço baseado na distância da viagem
distancia= float(input('Qual a distância da sua viagem em km? '))
print('Você está prestes a começar uma viagem de {:.0f}km.'.format(distancia))
if distancia <= 200:
  print('O preço da sua passagem é R${:.2f}'.format(distancia * 0.50))
else:
  print('O preço da sua passagem é R${:.2f}'.format(distancia * 0.45))

# 📝 Exercício 13: Solicita ao usuário um CPF ou CNPJ, remove caracteres não numéricos e retorna apenas os dígitos

documento= input("Digite o CPF ou CNPJ: ")
documento_limpo= ''.join(filter(str.isdigit, documento))
print(f"Documento limpo: {documento_limpo}")

# 📝 Exercício 14: Cálculo de valor da parcela de um financiamento de imóvel e verificação de aprovação com base em até 30% do salário do usuário

valor_casa= float(input('Qual é o valor do imóvel? R$'))
valor_salario= float(input('Qual é o seu salário? R$'))
tempo= int(input('Em quantos anos você quer financiar? R$'))
valor_parcela= valor_casa / (tempo * 12)
valor_mínimo= valor_salario * 30/100
print('Para pagar uma casa de R${:.2f} em {} anos'.format(valor_casa, tempo))
print('A prestação será de R${:.2f}'.format(valor_parcela))

if valor_parcela <= valor_mínimo:
  print('Empréstimo pode ser concedido.')
else:
  print('Empréstimo negado.')

# 📝 Exercício 15: Conversão um número inteiro digitado pelo usuário para binário, octal ou hexadecimal, de acordo com a opção escolhida

num= int(input('Digite um número inteiro: '))
print('''Escolha uma das bases para conversão:
[1] converter para binário
[2] converter para octal
[3] convertar para hexadecimal''')
opção= int(input('Sua opção: '))
if opção == 1:
  print('{} convertido para binário é igual a {}'.format(num, bin(num)[2:]))
elif opção == 2:
  print('{} convertido para octal é igual a {}'.format(num, oct(num)[2:]))
elif opção == 3:
  print('{} convertido para hexadecimal é igual a {}'.format(num, hex(num)[2:]))
else:
  print('Opção inválida, tente novamente')

# 📝 Exercício 16: Comparação de dois números inteiros digitados pelo usuário e informa qual é maior ou se são iguais

num1= int(input('Digite o primeiro valor: '))
num2= int(input('Digite o segundo valor: '))
if num1 > num2:
  print('Valor 1 é maior do que o Valor 2')
elif num2 > num1:
  print('Valor 2 é maior do que o Valor 1')
else:
  print('Os valores são iguais')

# 📝 Exercício 17: Cálculo da idade do usuário em 2025 e verifica a situação em relação ao alistamento militar obrigatório

ano_nascimento= int(input('Digite o ano de nascimento: '))
idade= 2025 - ano_nascimento
print ('Quem nasceu em {} tem {} anos em 2025'.format(ano_nascimento, idade))
tempo_faltante= 18 - idade
if idade < 18:
  print ('Ainda faltam {} anos para o alistamento'.format(tempo_faltante))
  print ('Seu alistamento será em {}'.format(ano_nascimento + 18))
elif idade > 18:
  print ('Você deveria ter se alistado a {} anos'.format(tempo_faltante * -1))
  print ('Seu alistamento foi em {}'.format(ano_nascimento + 18))
else:
  print ('Você tem 18 anos e deve se alistar imediatamente')

# 📝 Exercício 18: Lê duas notas, calcula a média e informa se o aluno foi aprovado, em recuperação ou reprovado

nota1= float(input('Digite a primeira nota: '))
nota2= float(input('Digite a segunda nota: '))
média= (nota1 + nota2) / 2
print('A média entre {} e {} é igual a {}'.format(nota1, nota2, média))
if média < 5:
  print('Aluno reprovado')
elif média > 5 and média < 6.9:
  print ('Aluno em recuperação')
else:
  print ('Aluno aprovado')

# 📝 Exercício 19: Cálculo a idade do usuário e classifica em categorias esportivas

ano= int(input('Digite seu ano de nascimento: '))
idade= 2025 - ano
print ('Quem nasceu em {} tem {} anos'.format(ano, idade))
if idade <= 9:
  print('Você faz parte da categora MIRIM')
elif idade > 9 and idade <= 14:
  print('Você faz parte da categoria INFANTIL')
elif idade > 14 and idade <= 19:
  print('Você faz parte da categoria JUNIOR')
elif idade > 19 and idade <= 25:
  print('Você faz parte da categoria SÊNIOR')
else:
  print('Você faz parte da categoria MASTER')

# 📝 Exercício 20: Cálculo automático da idade do usuário com base no ano de nascimento e o ano atual

from datetime import date
atual= date.today().year
nasc= int(input('Digite seu ano de nascimento: '))
idade= atual - nasc
print('Quem nasceu em {} tem {} anos em {}'.format(nasc, idade, atual))

# 📝 Exercício 21: Verifica se três segmentos podem formar um triângulo e, se sim, identifica se é equilátero, isósceles ou escaleno

r1= float(input('Primeiro segmento: '))
r2= float(input('Segundo segmento: '))
r3= float(input('Terceiro segmento: '))
if  r1 < r2 + r3 and r2 < r1 + r3 and r3 < r1 + r2:
  print('Os segmentos acima podem formar um triângulo', end=' ')
  if r1 == r2 == r3:
   print('equilátero')
  elif r1 != r2 != r3 != r1:
    print('escaleno')
  else:
    print('isósceles')
else:
  print('Os segmentos acima não podem formar um triângulo')

# 📝 Exercício 22: Cálculo e classificação de IMC

peso= float(input('Digite seu peso: '))
altura= float(input('Digite sua alttura: '))
imc= peso / (altura * altura)
print('Seu IMC é {:.2f}'.format(imc))
if imc <= 18.5:
  print('Abaixo do peso')
elif imc > 18.5 and imc <= 25:
  print('Peso ideal')
elif imc > 25 and imc <= 30:
  print('Sobrepeso')
elif imc > 30 and imc <= 40:
  print('Obesidade')
else:
  print('Obesidade mórbida')

# 📝 Exercício 23: Cálculo de valor final da compra de acordo com a forma de pagamento escolhida

preço= float(input('Preço das compras: R$'))
print ('''FORMA DE PAGAMENTO:
[1] À vista no dinheiro ou cheque
[2] À vista no cartão
[3] 2x no cartão
[4] 3x ou mais no cartão''')
opção= int(input('Qual é a opção? '))
if opção == 1:
  total= preço - (preço * 10/100)
elif opção ==2:
  total= preço - (preço * 5/100)
elif opção == 3:
  total = preço
  parcela = total / 2
  print('Sua compra será parcelada em 2x de R${:.2f}'.format(parcela))
elif opção == 4:
  total = preço + (preço * 20/100)
  total_parcelas= int(input('Quantas parcelas? '))
  parcela= total / total_parcelas
  print('Sua compra será parcelada em {}x de R${:.2f}'.format(total_parcelas, parcela))
else:
  total= 0
  print('Opção inválida, tente novamente')
print('Sua compra de {:.2f} vai custar {:.2f} no final'.format(preço,total))

# 📝 Exercício 24: Simulação do jogo Pedra, Papel e Tesoura, escolhendo aleatoriamente a jogada do computador e comparando com a jogada do jogador

from random import randint
itens= ('Pedra', 'Papel', 'Tesoura')
computador= randint(0, 2)
print('''Suas opções:
[0] Pedra
[1] Papel
[2] Tesoura''')
jogador= int(input('Qual é a sua jogada? '))
print('-='*11)
if jogador < 0 or jogador > 2:
  print('Jogada inválida')
else:
  print('O computador jogou {}'.format(itens[computador]))
  print('O jogador jogou {}'.format(itens[jogador]))
print('-='*11)
if computador == 0:
  if jogador == 0:
    print('Empate')
  elif jogador == 1:
    print('Jogador vence')
  elif jogador == 2:
    print ('Computador vence')
elif computador == 1:
  if jogador == 0:
    print('Computador vence')
  elif jogador == 1:
    print('Empate')
  elif jogador == 2:
    print('Jogador vence')
elif computador == 2:
  if jogador == 0:
    print('Jogador vence')
  elif jogador == 1:
    print('Computador vence')
  elif jogador == 2:
    print('Empate')